"""
Programmatic app/website boilerplate generator (Daily Mutton, SaaS shells, etc.).
"""

from __future__ import annotations

import json
import re
from typing import Any


def _slugify(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s or "omnimind-app"


def _strip_jsx_for_preview(source: str) -> str:
    """Remove ESM import/export for inline Babel preview."""
    out = re.sub(r"^import\s+.*?from\s+['\"].*?['\"];?\s*$", "", source, flags=re.M)
    out = re.sub(r"export\s+default\s+function\s+(\w+)", r"function \1", out)
    return out.strip()


def _parse_stack(message: str) -> dict[str, str]:
    low = message.lower()
    frontend = "vite"
    if re.search(r"frontend:\s*nextjs", low):
        frontend = "nextjs"
    elif re.search(r"frontend:\s*react-vite", low):
        frontend = "vite"
    elif re.search(r"frontend:\s*vanilla", low):
        frontend = "vanilla"
    elif re.search(r"frontend:\s*phaser", low):
        frontend = "phaser"
    elif re.search(r"frontend:\s*threejs", low):
        frontend = "threejs"

    backend = "none"
    if re.search(r"backend:\s*fastapi", low):
        backend = "fastapi"
    elif re.search(r"backend:\s*express", low):
        backend = "express"

    database = "manual"
    if "managed_mongo" in low or "database: managed_mongo" in low:
        database = "managed_mongo"
    elif "managed_supabase" in low:
        database = "managed_supabase"
    elif "sqlite_local" in low:
        database = "sqlite_local"

    email = ""
    m = re.search(r"contact:\s*(\S+@\S+\.\S+)", message, re.I)
    if m:
        email = m.group(1).strip()
    return {"frontend": frontend, "backend": backend, "database": database, "email": email}


def _extract_app_title(message: str) -> str:
    first_line = message.strip().split("\n")[0].strip()
    if first_line and first_line not in ("…", "...", "Build this full-stack project:"):
        cleaned = re.sub(r"^(build|create|make)\s+(this\s+)?(full-stack\s+)?(project:?\s*)?", "", first_line, flags=re.I)
        cleaned = cleaned.strip(" .,:\"'")
        if len(cleaned) > 2 and cleaned not in ("…", "..."):
            return cleaned.title()[:48]

    patterns = [
        r"(?:daily\s+)?mutton\s+app",
        r"(?:build|create|make)\s+(?:a\s+)?(.+?)\s+(?:app|website)",
        r"(.+?)\s+(?:app|website)\b",
    ]
    low = message.lower()
    if "mutton" in low:
        return "Daily Mutton"
    for pat in patterns:
        m = re.search(pat, message, re.I)
        if m:
            title = m.group(1).strip(" .,\"'")
            if len(title) > 2 and title.lower() not in ("frontend", "backend", "database"):
                return title.title()[:48]
    return "OmniMind App"


def _env_example(stack: dict[str, str]) -> str:
    lines = [
        "# Generated by OmniMind V11 Lead Architect",
        "NEXT_PUBLIC_BACKEND_URL=http://127.0.0.1:8001",
        f"FRONTEND_STACK={stack['frontend']}",
        f"BACKEND_STACK={stack['backend']}",
        f"DATABASE_MODE={stack['database']}",
    ]
    if stack["database"] == "managed_mongo":
        lines.append("# MongoDB Atlas — connection injected silently after cluster provision")
        lines.append("MONGODB_URI=<managed-by-omnimind-atlas>")
    elif stack["database"] == "managed_supabase":
        lines.append("DATABASE_URL=<managed-by-omnimind-supabase>")
        lines.append("NEXT_PUBLIC_SUPABASE_URL=<managed-by-omnimind>")
        lines.append("NEXT_PUBLIC_SUPABASE_ANON_KEY=<managed-by-omnimind>")
    if stack.get("email"):
        lines.append(f"# Provision contact: {stack['email']}")
    return "\n".join(lines) + "\n"


def _build_nextjs_fastapi_bundle(title: str, slug: str, stack: dict[str, str]) -> dict[str, Any]:
    accent = "#10b981"
    env_block = _env_example(stack)

    page_tsx = f"""export default function Home() {{
  return (
    <main className="min-h-screen bg-[#0B0C10] text-zinc-100">
      <header className="border-b border-emerald-500/20 px-6 py-4">
        <h1 className="text-2xl font-bold text-[#00FF87]">{title}</h1>
        <p className="text-sm text-zinc-500">Next.js · FastAPI · MongoDB Atlas</p>
      </header>
      <section className="mx-auto max-w-2xl space-y-4 p-6">
        <p className="text-zinc-300">
          Scaffold generated by OmniMind V11. Edit <code className="text-emerald-400">app/page.tsx</code> and
          connect your API at <code className="text-emerald-400">NEXT_PUBLIC_BACKEND_URL</code>.
        </p>
        <button
          type="button"
          className="rounded-lg px-4 py-2 font-semibold text-black"
          style={{{{ background: "{accent}" }}}}
        >
          Get started
        </button>
      </section>
    </main>
  );
}}
"""

    layout_tsx = """import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "OmniMind App",
  description: "Generated by OmniMind V11 Lead Architect",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
"""

    globals_css = """* { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, sans-serif; }
"""

    package_json = {
        "name": slug,
        "version": "1.0.0",
        "private": True,
        "scripts": {"dev": "next dev", "build": "next build", "start": "next start", "lint": "next lint"},
        "dependencies": {"next": "^15.0.0", "react": "^19.0.0", "react-dom": "^19.0.0"},
        "devDependencies": {
            "@types/node": "^22.0.0",
            "@types/react": "^19.0.0",
            "typescript": "^5.6.0",
        },
    }

    main_py = f'''"""FastAPI backend — {title}"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="{title}")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def root():
    return {{"ok": True, "app": "{title}", "stack": "fastapi"}}


@app.get("/api/health")
def health():
    return {{"status": "online", "database_mode": "{stack["database"]}"}}
'''

    requirements = "fastapi>=0.115.0\nuvicorn[standard]>=0.32.0\npymongo>=4.10.0\npython-dotenv>=1.0.0\n"

    readme = f"""# {title}

Generated by **OmniMind V11 Lead Architect**

| Layer | Stack |
|-------|-------|
| Frontend | Next.js 15 |
| Backend | FastAPI (port 8001) |
| Database | MongoDB Atlas (managed) |

## Local dev

```bash
# Backend
cd backend
python -m venv .venv
.venv\\\\Scripts\\\\activate   # Windows
pip install -r requirements.txt
uvicorn main:app --host 127.0.0.1 --port 8001 --reload

# Frontend (new terminal)
cd frontend
npm install
npm run dev
```

## Deploy

1. **Frontend** → Vercel (`vercel --prod` from `frontend/`)
2. **Backend** → Railway / Render / AWS EC2
3. Set `NEXT_PUBLIC_BACKEND_URL` in Vercel env
4. MongoDB Atlas IP allowlist + `MONGODB_URI` on backend host
"""

    files = [
        {"path": "frontend/package.json", "content": json.dumps(package_json, indent=2), "language": "json"},
        {"path": "frontend/app/page.tsx", "content": page_tsx, "language": "typescript"},
        {"path": "frontend/app/layout.tsx", "content": layout_tsx, "language": "typescript"},
        {"path": "frontend/app/globals.css", "content": globals_css, "language": "css"},
        {"path": "frontend/tsconfig.json", "content": json.dumps({"compilerOptions": {"jsx": "preserve", "strict": True, "paths": {"@/*": ["./*"]}}}, indent=2), "language": "json"},
        {"path": "backend/main.py", "content": main_py, "language": "python"},
        {"path": "backend/requirements.txt", "content": requirements, "language": "text"},
        {"path": ".env.example", "content": env_block, "language": "text"},
        {"path": "preview.html", "content": preview_html, "language": "html"},
        {"path": "README.md", "content": readme, "language": "markdown"},
    ]

    preview_html = f"""<!DOCTYPE html><html><head><title>{title}</title></head>
<body style="font-family:system-ui;background:#0B0C10;color:#eee;padding:24px">
<h1 style="color:#00FF87">{title}</h1>
<p>Next.js + FastAPI scaffold — open Code tab for full monorepo.</p>
</body></html>"""

    return {"title": title, "slug": slug, "files": files, "preview_html": preview_html}


def build_app_bundle(message: str) -> dict[str, Any]:
    stack = _parse_stack(message)
    title = _extract_app_title(message)
    slug = _slugify(title)

    if stack["frontend"] == "nextjs" and stack["backend"] == "fastapi":
        return _build_nextjs_fastapi_bundle(title, slug, stack)

    accent = "#00ff88" if "mutton" in message.lower() else "#38bdf8"

    package_json = {
        "name": slug,
        "version": "1.0.0",
        "private": True,
        "scripts": {"dev": "vite", "build": "vite build", "preview": "vite preview"},
        "dependencies": {"react": "^18.3.1", "react-dom": "^18.3.1"},
        "devDependencies": {"vite": "^5.4.0", "@vitejs/plugin-react": "^4.3.0"},
    }

    app_js = f"""import {{ useState }} from "react";

export default function App() {{
  const [qty, setQty] = useState(1);
  return (
    <div style={{{{ fontFamily: "system-ui", minHeight: "100vh", background: "#0a0f0c", color: "#e4e4e7", padding: 20 }}}}>
      <h1 style={{{{ color: "{accent}" }}}}>{title}</h1>
      <p>OmniMind V11 scaffold · cart items: {{qty}}</p>
      <button type="button" onClick={{() => setQty((q) => q + 1)}} style={{{{ padding: "8px 14px", borderRadius: 8, border: 0, background: "{accent}", cursor: "pointer" }}}}>Add</button>
    </div>
  );
}}
"""

    index_html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>{title}</title></head>
<body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>"""

    main_jsx = """import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";

createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
"""

    preview_html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>{title}</title></head>
<body><div id="root"></div><p style="font-family:system-ui;padding:12px;color:#666">Loading preview…</p></body></html>"""

    standalone_preview = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>{title}</title>
<script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
<script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
<style>html,body,#root{{margin:0;min-height:100%;}}</style></head>
<body><div id="root"></div>
<script type="text/babel">
const {{ useState }} = React;
{_strip_jsx_for_preview(app_js)}
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(React.createElement(App));
</script></body></html>"""

    files = [
        {"path": "package.json", "content": json.dumps(package_json, indent=2), "language": "json"},
        {"path": "src/App.jsx", "content": app_js, "language": "javascript"},
        {"path": "src/main.jsx", "content": main_jsx, "language": "javascript"},
        {"path": "index.html", "content": index_html, "language": "html"},
        {"path": "preview.html", "content": standalone_preview, "language": "html"},
        {"path": ".env.example", "content": _env_example(stack), "language": "text"},
        {
            "path": "README.md",
            "content": f"# {title}\n\nGenerated by OmniMind V11 App Builder.\n\n```bash\nnpm install && npm run dev\n```\n",
            "language": "markdown",
        },
    ]

    return {
        "title": title,
        "slug": slug,
        "files": files,
        "preview_html": standalone_preview,
    }
