import type { SDKGeneratorTemplate, SDKModuleKind, SDKModuleManifest, SDKProjectScaffold } from "../../shared/types";

const ENTERPRISE_FOLDERS = [
  "frontend",
  "backend",
  "api",
  "ai",
  "database",
  "testing",
  "assets",
  "docs",
  "config",
  "deployment",
  "localization",
  "security",
  "plugins",
  "workflows",
];

const TEMPLATE_CAPABILITIES: Record<SDKGeneratorTemplate, string[]> = {
  "medical-tool": ["analyze-medical-image"],
  "music-tool": ["generate-music", "voice-processing"],
  "video-tool": ["generate-video", "edit-video"],
  "image-tool": ["generate-video"],
  "business-tool": ["analyze-data", "marketing-campaign"],
  "finance-tool": ["financial-analysis", "analyze-data"],
  "developer-tool": ["generate-code", "deploy"],
  "research-tool": ["scientific-simulation", "analyze-data"],
  "productivity-tool": ["generate-code"],
  "game-tool": ["generate-code"],
  "enterprise-dashboard": ["analyze-data"],
  "chat-module": ["voice-processing"],
  "analytics-module": ["analyze-data"],
  "generic-tool": ["generate-code"],
};

export function defaultManifest(
  name: string,
  kind: SDKModuleKind,
  template: SDKGeneratorTemplate = "generic-tool",
): SDKModuleManifest {
  const id = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return {
    id,
    name: name.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
    version: "1.0.0",
    description: `OmniMind ${kind}: ${name}`,
    author: "OmniMind Developer",
    kind,
    template,
    route: `/${id}`,
    toolId: id,
    capabilities: TEMPLATE_CAPABILITIES[template],
    permissions: ["network", "filesystem"],
    dependencies: [],
    designSystem: true,
    autoRegister: true,
    minOmniVersion: "12.0.0",
  };
}

function sdkEntryContent(manifest: SDKModuleManifest): string {
  return `/**
 * ${manifest.name} — OmniMind SDK Module
 * Auto-registers with Brain, Memory, Plugins, Marketplace, Design System.
 */
import { getOmniMindSDK } from "@omnimind/sdk/browser";

const sdk = getOmniMindSDK();

export async function boot${manifest.name.replace(/\s/g, "")}() {
  const result = await sdk.register({
    ...manifest,
  });
  console.log("[${manifest.id}] registered:", result.targets);
  return result;
}

export const manifest = ${JSON.stringify(manifest, null, 2)} as const;

export function use${manifest.name.replace(/\s/g, "")}API() {
  return sdk.api;
}
`;
}

function pageContent(manifest: SDKModuleManifest): string {
  return `"use client";

import { DSWorkspaceHeader, DSCard } from "@/design-system";
import { use${manifest.name.replace(/\s/g, "")}API, boot${manifest.name.replace(/\s/g, "")} } from "../sdk/entry";
import { useEffect } from "react";

export default function ${manifest.name.replace(/\s/g, "")}Page() {
  const api = use${manifest.name.replace(/\s/g, "")}API();

  useEffect(() => {
    void boot${manifest.name.replace(/\s/g, "")}();
  }, []);

  return (
    <div className="flex h-full flex-col bg-[color:var(--omni-ds-bg-canvas)]">
      <DSWorkspaceHeader title="${manifest.name}" subtitle="${manifest.description}" />
      <DSCard className="m-4">
        <p className="text-[11px] text-[color:var(--omni-ds-text-primary)]">
          ${manifest.name} is connected to OmniMind Brain, Memory, and Plugin Framework.
        </p>
      </DSCard>
    </div>
  );
}
`;
}

function readmeContent(manifest: SDKModuleManifest): string {
  return `# ${manifest.name}

OmniMind V12 SDK module (${manifest.kind}).

## Quick start

\`\`\`bash
omnimind doctor
omnimind build
omnimind verify
\`\`\`

## SDK APIs

\`\`\`typescript
import { getOmniMindSDK } from "@omnimind/sdk/browser";

const sdk = getOmniMindSDK();
await sdk.register(manifest);
await sdk.api.ai.chat("Hello OmniMind");
\`\`\`

## Capabilities

${manifest.capabilities.map((c) => `- ${c}`).join("\n")}

## Architecture

See \`docs/ARCHITECTURE.md\` and OmniMind SDK reference.
`;
}

/** Generate enterprise folder structure + boilerplate files */
export function scaffoldProject(
  name: string,
  kind: SDKModuleKind,
  template: SDKGeneratorTemplate = "generic-tool",
): SDKProjectScaffold {
  const manifest = defaultManifest(name, kind, template);
  const files: SDKProjectScaffold["files"] = [];

  for (const folder of ENTERPRISE_FOLDERS) {
    files.push({ path: `${folder}/.gitkeep`, content: "" });
  }

  files.push({
    path: "omnimind.manifest.json",
    content: JSON.stringify(manifest, null, 2),
  });
  files.push({ path: "sdk/entry.ts", content: sdkEntryContent(manifest) });
  files.push({ path: `frontend/app/page.tsx`, content: pageContent(manifest) });
  files.push({ path: "README.md", content: readmeContent(manifest) });
  files.push({
    path: "docs/ARCHITECTURE.md",
    content: `# ${manifest.name} Architecture\n\nGenerated by OmniMind SDK.\n\nIntegrates: Brain, Memory, Plugins, Marketplace, Design System.\n`,
  });
  files.push({
    path: "config/omnimind.json",
    content: JSON.stringify({ sdkVersion: "12.0.0", module: manifest.id }, null, 2),
  });
  files.push({
    path: "testing/integration.test.ts",
    content: `import { describe, it, expect } from "vitest";
import { createMockSDK } from "@omnimind/sdk/browser";

describe("${manifest.id}", () => {
  it("boots with mock SDK", async () => {
    const mock = createMockSDK();
    expect(mock.api).toBeDefined();
  });
});
`,
  });
  files.push({
    path: "backend/main.py",
    content: `"""${manifest.name} backend — FastAPI stub"""
from fastapi import FastAPI

app = FastAPI(title="${manifest.name}")

@app.get("/health")
def health():
    return {"ok": True, "module": "${manifest.id}"}
`,
  });
  files.push({
    path: "ai/pipeline.ts",
    content: `import { getUniversalAPI } from "@omnimind/sdk/browser";

export async function runPipeline(input: string) {
  const api = getUniversalAPI();
  return api.ai.chat(input, { toolId: "${manifest.toolId}" });
}
`,
  });

  return {
    rootDir: name,
    manifest,
    files,
  };
}

export const GENERATOR_TEMPLATES: SDKGeneratorTemplate[] = [
  "medical-tool",
  "music-tool",
  "video-tool",
  "image-tool",
  "business-tool",
  "finance-tool",
  "developer-tool",
  "research-tool",
  "productivity-tool",
  "game-tool",
  "enterprise-dashboard",
  "chat-module",
  "analytics-module",
  "generic-tool",
];
