import type { AnalyticsInsight, BusinessRecommendation, DatasetSnapshot, ReportFormat, ReportKind } from "./types";

export function generateBusinessRecommendations(
  dataset: DatasetSnapshot | null,
  insights: AnalyticsInsight[],
): BusinessRecommendation[] {
  const recs: BusinessRecommendation[] = [];

  if (dataset?.report.issues.some((i) => i.kind === "duplicate")) {
    recs.push({
      id: "rec-cost",
      area: "cost",
      title: "Reduce data processing waste",
      why: "Duplicate rows inflate storage and skew aggregates — cleaning improves decision accuracy and lowers compute cost.",
      impact: "medium",
    });
  }

  const regional = insights.find((i) => i.category === "regional");
  if (regional) {
    recs.push({
      id: "rec-marketing",
      area: "marketing",
      title: `Scale campaigns in ${regional.value ?? "top region"}`,
      why: regional.explanation,
      impact: "high",
    });
    recs.push({
      id: "rec-expansion",
      area: "expansion",
      title: "Replicate top-region playbook",
      why: "High-performing region patterns can be templated to underperforming areas with localized offers.",
      impact: "high",
    });
  }

  const profit = insights.find((i) => i.category === "profitability");
  if (profit?.trend === "down") {
    recs.push({
      id: "rec-pricing",
      area: "pricing",
      title: "Review pricing and discount policy",
      why: profit.explanation,
      impact: "high",
    });
    recs.push({
      id: "rec-risk",
      area: "risk",
      title: "Margin protection program",
      why: "Declining profitability increases exposure to supply shocks — hedge inventory and renegotiate vendor terms.",
      impact: "medium",
    });
  } else {
    recs.push({
      id: "rec-profit",
      area: "profit",
      title: "Optimize high-margin SKUs",
      why: "Healthy margins suggest room to prioritize profitable lines in merchandising and promotions.",
      impact: "medium",
    });
  }

  recs.push({
    id: "rec-inventory",
    area: "inventory",
    title: "Align inventory to forecast peaks",
    why: "Seasonality signals indicate when to pre-build stock — reduces stockouts without overholding.",
    impact: "medium",
  });

  return recs;
}

export function generateReportMarkdown(
  kind: ReportKind,
  dataset: DatasetSnapshot | null,
  insights: AnalyticsInsight[],
): string {
  const title = {
    executive: "Executive Summary",
    technical: "Technical Analytics Report",
    business: "Business Performance Report",
    investor: "Investor Brief",
  }[kind];

  return `# ${title}

Generated by OmniMind Enterprise Analytics · ${new Date().toLocaleDateString()}

## Dataset
${dataset ? `${dataset.name} · ${dataset.rows.length} rows · ${dataset.headers.length} columns` : "No dataset loaded"}

## Key Insights
${insights.map((i) => `### ${i.title}\n${i.explanation}\n*Confidence: ${Math.round(i.confidence * 100)}%*`).join("\n\n")}

## Recommendations
See AI Business Advisor panel for actionable next steps.
`;
}

export function downloadTextReport(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportDatasetCsv(dataset: DatasetSnapshot): string {
  const header = dataset.headers.join(",");
  const lines = dataset.rows.map((r) => dataset.headers.map((h) => JSON.stringify(r[h] ?? "")).join(","));
  return [header, ...lines].join("\n");
}

export function triggerExport(format: ReportFormat | "csv" | "json" | "png" | "svg", payload: {
  dataset?: DatasetSnapshot | null;
  reportMd?: string;
  chartSvg?: string;
}) {
  if (format === "csv" && payload.dataset) {
    downloadTextReport(exportDatasetCsv(payload.dataset), `${payload.dataset.name}.csv`);
    return;
  }
  if ((format === "markdown" || format === "pdf" || format === "word") && payload.reportMd) {
    downloadTextReport(payload.reportMd, `omnimind-report.${format === "markdown" ? "md" : "txt"}`);
    return;
  }
  if (format === "json" && payload.dataset) {
    downloadTextReport(JSON.stringify(payload.dataset.rows, null, 2), `${payload.dataset.name}.json`);
    return;
  }
  if ((format === "svg" || format === "png") && payload.chartSvg) {
    downloadTextReport(payload.chartSvg, `chart.${format}`);
  }
}
