import type { ArchitectAnalysis } from "../omniforge-architect-api";
import type { ArchitectBlueprint, TechStackSelection, WizardState } from "./types";
import { labelForProjectType } from "./wizard-config";

export function blueprintFromAnalysis(
  analysis: ArchitectAnalysis,
  stack: TechStackSelection,
  projectName: string,
): ArchitectBlueprint {
  return {
    architecture: `${analysis.domain_label} · ${analysis.target_stack} stack with ${stack.frontend} + ${stack.backend}`,
    folderStructure: analysis.folder_tree.length
      ? analysis.folder_tree
      : ["src/", "src/components/", "src/pages/", "backend/", "tests/", "docs/"],
    databaseSchema: `Primary DB: ${stack.database} (${analysis.database.reason})`,
    apiPlan: `REST API at ${analysis.routing.api_prefix} · Frontend routes: ${analysis.routing.frontend}`,
    authPlan: `${analysis.auth.strategy} · Providers: ${analysis.auth.providers.join(", ") || "email"} · JWT: ${analysis.auth.jwt}`,
    deploymentPlan: `Deploy to ${stack.deployment} with Docker-ready artifacts`,
    securityPlan: "Env secrets, HTTPS, input validation, rate limiting, OWASP headers",
    testingPlan: "Unit tests (core logic), integration tests (API), smoke tests (CI)",
    performancePlan: "Code splitting, lazy routes, DB indexes, CDN for static assets",
  };
}

export function generateReadme(wizard: WizardState, blueprint: ArchitectBlueprint | null): string {
  const typeLabel = wizard.projectType ? labelForProjectType(wizard.projectType) : "Application";
  return `# ${wizard.projectName || "OmniForge Project"}

> ${typeLabel} — generated by OmniForge Engineering Suite

## Description

${wizard.description || "AI-generated production scaffold."}

## Tech Stack

| Layer | Choice |
|-------|--------|
| Frontend | ${wizard.stack.frontend} |
| Backend | ${wizard.stack.backend} |
| Database | ${wizard.stack.database} |
| ORM | ${wizard.stack.orm} |
| Deploy | ${wizard.stack.deployment} |

## Architecture

${blueprint?.architecture ?? "See docs/ARCHITECTURE.md"}

## Quick Start

\`\`\`bash
# Install dependencies
npm install

# Start development
npm run dev
\`\`\`

## Environment

Copy \`.env.example\` to \`.env\` and fill required variables.

## License

MIT
`;
}

export function generateArchitectureDoc(blueprint: ArchitectBlueprint): string {
  return `# Architecture

## Overview

${blueprint.architecture}

## Folder Structure

\`\`\`
${blueprint.folderStructure.join("\n")}
\`\`\`

## Database

${blueprint.databaseSchema}

## API

${blueprint.apiPlan}

## Authentication

${blueprint.authPlan}

## Security

${blueprint.securityPlan}

## Testing

${blueprint.testingPlan}

## Performance

${blueprint.performancePlan}

## Deployment

${blueprint.deploymentPlan}
`;
}

export function generateApiDoc(analysis: ArchitectAnalysis | null): string {
  const prefix = analysis?.routing.api_prefix ?? "/api/v1";
  return `# API Documentation

Base URL: \`${prefix}\`

## Endpoints

| Method | Path | Description |
|--------|------|-------------|
| GET | ${prefix}/health | Health check |
| POST | ${prefix}/auth/login | Authenticate user |
| GET | ${prefix}/users | List users |
| POST | ${prefix}/users | Create user |

> Auto-generated from architect plan — extend as routes are implemented.
`;
}

export function generateDeploymentGuide(stack: TechStackSelection): string {
  return `# Deployment Guide

Target platform: **${stack.deployment}**

## Steps

1. Build production assets: \`npm run build\`
2. Set environment variables (see ENV.md)
3. Deploy via ${stack.deployment} CLI or dashboard
4. Run database migrations
5. Verify health endpoint

## Docker

\`\`\`bash
docker build -t app .
docker run -p 3000:3000 --env-file .env app
\`\`\`
`;
}

export function generateEnvGuide(analysis: ArchitectAnalysis | null): string {
  const bindings = analysis?.env_bindings ?? [
    { key: "DATABASE_URL", scope: "backend" },
    { key: "JWT_SECRET", scope: "backend" },
    { key: "NEXT_PUBLIC_API_URL", scope: "frontend" },
  ];
  return `# Environment Variables

| Variable | Scope | Description |
|----------|-------|-------------|
${bindings.map((b) => `| \`${b.key}\` | ${b.scope} | Required for ${b.scope} |`).join("\n")}
`;
}

export function generateDatabaseGuide(stack: TechStackSelection, blueprint: ArchitectBlueprint | null): string {
  return `# Database Guide

Engine: **${stack.database}** · ORM: **${stack.orm}**

${blueprint?.databaseSchema ?? ""}

## Migrations

Run migrations after schema changes. Keep seeds idempotent for CI.
`;
}

export type GeneratedDocSet = {
  path: string;
  content: string;
}[];

export function generateAllDocs(
  wizard: WizardState,
  blueprint: ArchitectBlueprint | null,
  analysis: ArchitectAnalysis | null,
): GeneratedDocSet {
  const archDoc =
    blueprint ??
    (analysis
      ? blueprintFromAnalysis(analysis, wizard.stack, wizard.projectName)
      : {
          architecture: `${wizard.projectName} — ${wizard.stack.frontend} + ${wizard.stack.backend}`,
          folderStructure: ["src/", "backend/", "docs/"],
          databaseSchema: `Database: ${wizard.stack.database}`,
          apiPlan: "REST API with versioned routes",
          authPlan: "JWT session-based authentication",
          deploymentPlan: `Deploy to ${wizard.stack.deployment}`,
          securityPlan: "Env secrets, HTTPS, input validation",
          testingPlan: "Unit + integration tests",
          performancePlan: "Lazy loading, caching, CDN",
        });

  return [
    { path: "README.md", content: generateReadme(wizard, archDoc) },
    { path: "docs/ARCHITECTURE.md", content: generateArchitectureDoc(archDoc) },
    { path: "docs/API.md", content: generateApiDoc(analysis) },
    { path: "docs/DEPLOYMENT.md", content: generateDeploymentGuide(wizard.stack) },
    { path: "docs/ENV.md", content: generateEnvGuide(analysis) },
    { path: "docs/DATABASE.md", content: generateDatabaseGuide(wizard.stack, archDoc) },
  ];
}
