export type DocKind =
  | "readme"
  | "architecture"
  | "api"
  | "database"
  | "deployment"
  | "developer"
  | "user";

export type GeneratedDoc = { kind: DocKind; path: string; content: string };

type FileSnapshot = { path: string; content: string };

/** Generates full documentation suite for enterprise projects. */
export function generateEnterpriseDocs(
  projectName: string,
  blueprint: { architecture: string; databaseSchema: string; apiPlan: string; deploymentPlan: string },
  files: FileSnapshot[],
): GeneratedDoc[] {
  const fileList = files.map((f) => `- \`${f.path}\``).join("\n");

  return [
    {
      kind: "readme",
      path: "README.md",
      content: `# ${projectName}\n\nEnterprise project generated by OmniForge.\n\n## Files\n${fileList}\n`,
    },
    {
      kind: "architecture",
      path: "docs/ARCHITECTURE.md",
      content: `# Architecture — ${projectName}\n\n${blueprint.architecture}\n`,
    },
    {
      kind: "api",
      path: "docs/API.md",
      content: `# API Documentation\n\n${blueprint.apiPlan}\n`,
    },
    {
      kind: "database",
      path: "docs/DATABASE.md",
      content: `# Database\n\n${blueprint.databaseSchema}\n`,
    },
    {
      kind: "deployment",
      path: "docs/DEPLOYMENT.md",
      content: `# Deployment Guide\n\n${blueprint.deploymentPlan}\n`,
    },
    {
      kind: "developer",
      path: "docs/DEVELOPER.md",
      content: `# Developer Guide\n\n\`\`\`bash\nnpm install && npm run dev\n\`\`\`\n`,
    },
    {
      kind: "user",
      path: "docs/USER_GUIDE.md",
      content: `# User Guide — ${projectName}\n`,
    },
  ];
}
