"""Generate platform API reference table — run from repo root."""
from __future__ import annotations

import re
from pathlib import Path

ROUTERS = Path(__file__).resolve().parents[1] / "backend" / "routers"
PLATFORM_KEYS = (
    "omnicore",
    "medical_enterprise",
    "visionary_studio",
    "omnimusic_studio",
    "platform_ops",
)


def is_platform(name: str) -> bool:
    return any(k in name for k in PLATFORM_KEYS)


def main() -> None:
    rows: list[tuple[str, str, str]] = []
    for path in sorted(ROUTERS.glob("*.py")):
        if not is_platform(path.stem):
            continue
        src = path.read_text(encoding="utf-8")
        prefix_m = re.search(r'prefix=["\']([^"\']+)["\']', src)
        prefix = prefix_m.group(1) if prefix_m else ""
        for m in re.finditer(
            r'@router\.(get|post|put|patch|delete)\(["\']([^"\']*)["\']',
            src,
            re.I,
        ):
            method = m.group(1).upper()
            sub = m.group(2)
            if sub.startswith("/"):
                full = prefix + sub
            elif sub:
                full = f"{prefix}/{sub}"
            else:
                full = prefix
            rows.append((method, full, path.stem))

    rows.sort(key=lambda r: (r[1], r[0]))
    out = Path(__file__).parent / "API_REFERENCE.md"
    lines = [
        "# OmniMind API Reference",
        "",
        "**Version:** V12 Enterprise",
        "**Base URL:** `https://api.omnimind.app` (production) · `http://localhost:8001` (local)",
        "",
        "Interactive OpenAPI: `{base}/docs` (development/testing only).",
        "",
        "## Authentication",
        "",
        "Platform routes require `Authorization: Bearer <access_token>` except public probes:",
        "",
        "- `GET /api/v1/platform/health`",
        "- `GET /api/v1/platform/live`",
        "- `GET /api/v1/platform/ready`",
        "",
        "Obtain tokens via `POST /api/v1/auth/login`. Write operations require `operator` role or higher.",
        "",
        "## Platform modules (auto-generated)",
        "",
        f"**Total platform endpoints:** {len(rows)}",
        "",
        "| Method | Path | Router |",
        "|--------|------|--------|",
    ]
    for method, full, stem in rows:
        lines.append(f"| {method} | `{full}` | `{stem}` |")
    lines.extend(
        [
            "",
            "## Full API surface",
            "",
            "OmniMind exposes 80+ routers across tools, entertainment, science, and platform domains.",
            "See [ARCHITECTURE.md](ARCHITECTURE.md) for module boundaries.",
            "",
            "> Generated by `docs/_gen_api_ref.py` — regenerate after router changes.",
            "",
        ]
    )
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} endpoints to {out}")


if __name__ == "__main__":
    main()
