import type { GeneratedFileAsset } from "./execution-preview";
import { getBackendUrl } from "./backend-url";
import type { ArchitectFlowSelections } from "./architect-flow";
import { buildScaffoldMessage } from "./architect-flow";

const DB_STORAGE_KEY = "omnimind_architect_db_config";

export type DbProvisionResult = {
  success: boolean;
  provider?: string;
  injected?: boolean;
  message?: string;
};

export async function provisionManagedDatabase(payload: {
  email: string;
  provider: "supabase" | "mongodb_atlas";
  projectPrompt?: string;
}): Promise<DbProvisionResult> {
  const base = getBackendUrl();
  const res = await fetch(`${base}/api/v1/build/provision-db`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      email: payload.email,
      provider: payload.provider,
      project_prompt: payload.projectPrompt ?? "",
    }),
  });
  const data = (await res.json()) as DbProvisionResult;
  if (data.success && data.injected && typeof window !== "undefined") {
    sessionStorage.setItem(
      DB_STORAGE_KEY,
      JSON.stringify({ provider: payload.provider, at: Date.now() }),
    );
  }
  return data;
}

export async function scaffoldArchitectProject(
  selections: ArchitectFlowSelections,
  userId = "guest-founder",
): Promise<{ title: string; files: GeneratedFileAsset[] }> {
  const base = getBackendUrl();
  const message = buildScaffoldMessage(selections);
  const res = await fetch(`${base}/api/v1/build/app/scaffold`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ message, user_id: userId }),
  });
  if (!res.ok) {
    throw new Error(`Scaffold failed (${res.status})`);
  }
  const data = (await res.json()) as {
    title?: string;
    files?: { path: string; content: string; language?: string }[];
  };
  const files: GeneratedFileAsset[] = (data.files ?? []).map((f) => ({
    path: f.path,
    content: injectEnvIntoScaffold(f, selections),
    language: f.language,
  }));
  return { title: data.title ?? "OmniMind App", files };
}

function injectEnvIntoScaffold(
  file: { path: string; content: string },
  selections: ArchitectFlowSelections,
): string {
  if (!file.path.endsWith(".env.example") && file.path !== "README.md") {
    return file.content;
  }
  const lines = [
    `# Generated by OmniMind V11 Architect`,
    `NEXT_PUBLIC_BACKEND_URL=http://127.0.0.1:8001`,
    `FRONTEND_STACK=${selections.frontendId ?? "nextjs"}`,
    `BACKEND_STACK=${selections.backendId ?? "fastapi"}`,
    `DATABASE_MODE=${selections.databaseId ?? "manual"}`,
  ];
  if (selections.databaseId?.startsWith("managed_")) {
    lines.push(`# Connection string injected silently — see session: omnimind_architect_db_config`);
    lines.push(`DATABASE_URL=<managed-by-omnimind>`);
  }
  const block = lines.join("\n");
  if (file.path.endsWith(".env.example")) return `${block}\n`;
  return `${file.content}\n\n## Environment\n\`\`\`env\n${block}\n\`\`\`\n`;
}

export async function triggerDeployCliHook(payload: {
  deployId: string;
  selections: ArchitectFlowSelections;
}): Promise<{ ok: boolean; commands: string[] }> {
  const res = await fetch("/api/architect/deploy-hook", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });
  if (!res.ok) {
    return { ok: false, commands: [] };
  }
  return (await res.json()) as { ok: boolean; commands: string[] };
}
