export { OmniMusicStudioShell } from "./OmniMusicStudioShell";
export { OmniMusicWorkspace } from "./OmniMusicWorkspace";
export { MusicSidebar } from "./MusicSidebar";
export { TransportBar } from "./TransportBar";
export { TrackTimeline } from "./TrackTimeline";
export { MixerConsole } from "./MixerConsole";
export { PianoRoll } from "./PianoRoll";
export { ClipLauncher } from "./ClipLauncher";
export { AudioEditor } from "./AudioEditor";
export { MidiEditor } from "./MidiEditor";
export { PluginRack } from "./PluginRack";
export { InstrumentBrowser } from "./InstrumentBrowser";
export { SampleBrowser } from "./SampleBrowser";
export { LoopBrowser } from "./LoopBrowser";
export { RecordingPanel } from "./RecordingPanel";
export { AutomationEditor } from "./AutomationEditor";
export { EffectsBrowser } from "./EffectsBrowser";
export { MasterChannel } from "./MasterChannel";
export { ExportCenter } from "./ExportCenter";
export { StatusBar } from "./StatusBar";
export { InspectorPanel } from "./InspectorPanel";
export * from "./audio";
export * from "./ai";
export * from "./vocal";
export * from "./mixing";
